name: Feature Request
description: Suggest a new idea or feature for the project
labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        **Please describe the problem or feature you'd like to request.**
        Explain why you think this feature would be useful and any background context.

  - type: input
    attributes:
      label: Describe the feature or enhancement
      placeholder: "Provide a clear and concise description of the feature."
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      placeholder: "Add any other context, screenshots, or examples that might help explain this feature request."
      required: false

  - type: checkboxes
    attributes:
      label: Will this feature require new dependencies?
      options:
        - Yes, this feature will need new dependencies.
        - No, this feature does not require new dependencies.
      required: false

  - type: input
    attributes:
      label: Suggested Priority
      description: "Indicate if this feature is a high, medium, or low priority."
      placeholder: "High, Medium, Low"
      required: false
